/*
 * 집합 연산자
 * */
-- 1. UNION
-- 두개 이상의 쿼리 결과를 합쳐서 보여줌(중복 표시) 
-- 조건: 소속팀이 K02인 선수와 K07인 선수를 모두 출력
-- WHERE IN 조건과 같은 결과
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION 
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER 
WHERE TEAM_ID = 'K07';

-- 조건: 소속팀이 K02이거나 골기퍼인 선수들 모두 출력
-- WHERE 절의 OR과 같은 결과
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION 
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER 
WHERE POSITION = 'GK';

-- 조건: 포지션별 평균키와 팀별 평균키 집합의 합집합
SELECT 'P' 구분코드, POSITION, AVG(HEIGHT) 평균키
FROM PLAYER 
GROUP BY POSITION
UNION
SELECT 'T' 구분코드, TEAM_ID, AVG(HEIGHT) 평균키
FROM PLAYER 
GROUP BY TEAM_ID
ORDER BY 1;


-- 2. UNION ALL
-- UNION과 같은 기능이지만 중복을 제거해주는 차이점이 있음
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION ALL
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER 
WHERE POSITION = 'GK';


-- 3. EXCEPT, MINUS
-- 앞의 집합에서 뒤의 집합 빼기 (EXCEPT - SQL Server, MINUS - ORACLE)
-- 조건: 소속이 K02인 선수들의 집합과 K-리그 소속 선수 중 표지션이 MF인 선수들은 제외한 집합
-- ㄴ WHERE 절에 조건 추가하는 방법으로 대체 가능
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K02'
EXCEPT
SELECT PLAYER_NAME, TEAM_ID, POSITION, BACK_NO 
FROM PLAYER 
WHERE POSITION = 'MF';


-- 위 조건 대체 방법 (5장에서 자세히)
-- NOT EXISTS
SELECT P1.TEAM_ID, P1.PLAYER_NAME, P1."POSITION"
FROM PLAYER P1
WHERE P1.TEAM_ID = 'K02'
	AND NOT EXISTS(SELECT 1
				   FROM PLAYER P2 
				   WHERE P2.PLAYER_ID = P1.PLAYER_ID 
				   		AND "POSITION" = 'MF');
				   	

-- NOT IN
SELECT P1.TEAM_ID, P1.PLAYER_NAME, P1."POSITION" 
FROM PLAYER P1
WHERE P1.TEAM_ID = 'K02'
	AND PLAYER_ID NOT IN(SELECT P2.PLAYER_ID
						 FROM PLAYER P2
						 WHERE P2."POSITION" = 'MF');
				   	

-- 4. INTERSECT
-- 앞의 집합과 뒤의 집합의 공통 부분만 출력
-- 조건: 소속팀이 K02이면서 포지션이 GK인 선수들 출력
-- ㄴ WHERE 절 AND 추가, EXISTS, IN 방식으로 대체 가능
SELECT *
FROM PLAYER 
WHERE TEAM_ID = 'K02'
INTERSECT
SELECT *
FROM PLAYER
WHERE POSITION = 'GK';

-- 위 조건 대체 방법 (5장에서 자세히)
-- EXISTS
SELECT *
FROM PLAYER P1
WHERE P1.TEAM_ID = 'K02'
	AND EXISTS(SELECT 1 
			   FROM PLAYER P2 
			   WHERE P1.PLAYER_ID = P2.PLAYER_ID 
			   	AND P2."POSITION" = 'GK');
			   
-- IN
SELECT *
FROM PLAYER P1
WHERE P1.TEAM_ID = 'K02'
	AND P1.PLAYER_ID IN (SELECT P2.PLAYER_ID 	
						 FROM PLAYER P2
						 WHERE P2."POSITION" = 'GK');